### ISSUE TITLE
 Documentación sección técnicas y herramientas

### ISSUE THREAD

**Issue by cgc0045** [cgc0045/GESPRO_Practicas#10]
Indicar una visión general de la herramienta. Descripción funcional breve. Para qué se utiliza en la herramienta en el proyecto y referenciar a Web o libro.
SonarQube OpenShift
Jira Issues
Git IntelliJ Java LateX ....
[memoria_tecnicas_herramientas.pdf](https://github.com/cgc0045/GESPRO_Practicas/files/588903/memoria_tecnicas_herramientas.pdf)
[clopezno_memoria_tecnicas_herramientas.pdf](https://github.com/cgc0045/GESPRO_Practicas/files/588904/clopezno_memoria_tecnicas_herramientas.pdf)

**Comment by ysi0000** [comment]
attached memoria_tecnicas_herramientas.pdf
Adjunto una versión provisional del apartado Técnicas y Herramientas de la memoria.

**Comment by cgc0045** [comment]
attached clopezno_memoria_tecnicas_herramientas.pdf
Adjunto una revisión con comentarios sobre el pdf.
