### ISSUE TITLE
Manual de instalación de SonarQube

### ISSUE THREAD

**Issue by cgc0045** [cgc0045/GESPRO_Practicas#11]
Anexo de la memoria En Open shift En Local

[Manual de usuario.pdf](https://github.com/cgc0045/GESPRO_Practicas/files/588908/Manual.de.usuario.pdf)
[RevPlammenManual de usuario.pdf](https://github.com/cgc0045/GESPRO_Practicas/files/588909/RevPlammenManual.de.usuario.pdf)

**Comment by ysi0000** [comment]
Adjunto el anexo Manual de Usuario, en el que se explica cómo desplegar la instancia de SonarQube en local y en la plataforma OpenShift, cómo analizar un proyecto y la instalación de todas las herramientas utilizadas en los dos procesos anteriores.

**Comment by cgc0045** [comment]
Esta tarea ha sido resuelta en la issue #16 por considerar la creación de un apéndice adicional del el anexo, que incluya el despliegue de la instancia de SonarQube.
