### ISSUE TITLE
 Manual para escanear un Proyecto

### ISSUE THREAD

**Issue by cgc0045** [cgc0045/GESPRO_Practicas#12]
Hablar de los ficheros de configuración dependiendo del lenguaje
Comprobar la ejecución de Test Interesante un video tutorial ActivePresenter en Windows
[anexo-manual-usuario.pdf](https://github.com/cgc0045/GESPRO_Practicas/files/588911/anexo-manual-usuario.pdf)
[revclopezno_anexo-manual-usuario.pdf](https://github.com/cgc0045/GESPRO_Practicas/files/588912/revclopezno_anexo-manual-usuario.pdf)

**Comment by cgc0045** [comment]
Corregidos fallos en el manual de usuario en el que se explica como realizar análisis de proyectos con los distintos scanner de SonarQube

**Comment by ysi0000** [comment]
He probado los manuales de usuario referentes a SonarQube Scanner y SonarQube Scanner for MSBuild y siguiendo sus pasos he conseguido escanear los proyectos de la primera convocatoria (PHP. Java y C#). He dejado los resultados en la instancia de SonnarQube.
Creo que es la mejor forma de probar la calidad de tu documentación ;-)
