### ISSUE TITLE
 Crear trabajos relacionados de la memoria

### ISSUE THREAD

**Issue by cgc0045** [cgc0045/GESPRO_Practicas#15]
Comparar a nivel funcional con OpenHub https://www.openhub.net/ Añadir una tabla comparativa.
[memoria_trabajos_relacionados.pdf](https://github.com/cgc0045/GESPRO_Practicas/files/588917/memoria_trabajos_relacionados.pdf)

**Comment by ysi0000** [comment]
attached memoria_trabajos_relacionados.pdf
Adjunto el apartado Trabajos Relacionados de la memoria
