### ISSUE TITLE
 Incorporar nuevos proyectos en la instancia de SonarQube

### ISSUE THREAD

**Issue by cgc0045** [cgc0045/GESPRO_Practicas#20]
Incluir análisis de más trabajos fin de grado en la instancia de SonarQube. Incluir además proyectos presentados en la primera convocatoria 2016.

**Comment by ysi0000** [comment]
Incorporados los siguientes proyectos:
Estimación de biomasaforestal a partir de imágenes aéreas y LIDAR.
UBUGRAPH 4.0
Aplicación Fitness para Android
EasyBot para Android
Filmoteca Android
Sistema de estimación de edad a partir de radiografías dentales
Resolución Puzzle Android
Chameleon Sensor 1.0
Se han re-escaneado los demás proyectos para incluir la fecha de presentación en el nombre de los mismos.
