### ISSUE TITLE
Apéndice B: Especificación de Requisitos

### ISSUE THREAD

**Issue by cgc0045** [cgc0045/GESPRO_Practicas#27]
Crear la documentación correspondiente al apéndice Especificación de Requisitos
[anexos_especificacion_requisitos.pdf](https://github.com/cgc0045/GESPRO_Practicas/files/588957/anexos_especificacion_requisitos.pdf)

**Comment by ysi0000** [comment]
attached anexos_especificacion_requisitos.pdf
Adjunto la documentación correspondiente al apéndice Especificación de Requisitos
